---
output: github_document
---

# Astrocytes editing

## Background

This repository contains analysis code for the publication found [here](), which explored the response of astrocytes, neurons and astro-neuronal co-cultures to alpha-synuclein oligomers. The analysis includes work shared between two repositories:

- The repository at [https://github.com/karishdsa/ipscAstrNeurCocul](https://github.com/karishdsa/ipscAstrNeurCocul) contains single cell and bulk RNA sequencing analysis of the cell culture models utilised in the study.
- This current repository contains the analysis of RNA editing in the cell culture models, as well as in a [published dataset](https://link.springer.com/article/10.1007/s00401-021-02343-x) of post-mortem brain samples.


## Index

| No. | Title | Description |
| --- | --- | --- | 
| 01 | [Astrocyte Analysis](01_astrocyte_analysis.html) | Editing analysis of astrocyte and astro-neuronal co-cultures |
| 01 | [Brain Analysis](02_brain_analysis.html) | Editing analysis of post mortem brain samples |
